#!/usr/bin/env bash
# Install nginx web server
# Redirection

sudo apt update -y
sudo apt install nginx -y
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me https://youtu.be/LNv9PevSRLo permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/error404.html
sed -i "/server_name _;/ a\\\terror_page 404 \/error404.html;\n\tlocation = \/error404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}" /etc/nginx/sites-enabled/default
sudo service nginx start
