#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times with until
a=1
while (( a <= 10 ))
	do
		if [ "$a" -ne 9 ]
			then
				echo "Holberton School"
			else
				echo "Holberton School" ; echo "Hi"
		fi
		(( a ++ ))
	done