#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times with until
a=1
while (( a <= 10 ))
	do
		if [ "$a" -eq 4 ]
			then
				echo "bad luck"
		elif [ "$a" -eq 8 ]
			then
				echo "good luck"
		else
			echo "Holberton School"
		fi
		(( a ++ ))
	done